/**
 * GENERATED FILE — do not edit by hand.
 * Source of truth: migrations/*.sql (drizzle-kit generate).
 * Regenerate with: node scripts/embed-migrations.mjs
 */

/** Ordered migrations; each entry is the statement list of one SQL file. */
export const EMBEDDED_MIGRATIONS: readonly (readonly string[])[] = [
  // 0000_init.sql
  [
    "CREATE TABLE `assistance_requests` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`fan_session_id` text NOT NULL,\n\t`zone_id` text NOT NULL,\n\t`category` text NOT NULL,\n\t`description` text NOT NULL,\n\t`status` text DEFAULT 'open' NOT NULL,\n\t`client_request_id` text NOT NULL,\n\t`task_id` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`fan_session_id`) REFERENCES `fan_sessions`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`task_id`) REFERENCES `tasks`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `assistance_client_request_unique` ON `assistance_requests` (`client_request_id`);",
    "CREATE TABLE `audit_events` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`actor` text NOT NULL,\n\t`actor_role` text NOT NULL,\n\t`action` text NOT NULL,\n\t`resource` text NOT NULL,\n\t`resource_id` text NOT NULL,\n\t`before_hash` text,\n\t`after_hash` text,\n\t`reason` text,\n\t`correlation_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `audit_venue_time_idx` ON `audit_events` (`venue_id`,`created_at`);",
    "CREATE INDEX `audit_correlation_idx` ON `audit_events` (`venue_id`,`correlation_id`);",
    "CREATE TABLE `congestion_scenarios` (\n\t`gate_id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`state` text NOT NULL,\n\t`arrival_rate` real DEFAULT 0 NOT NULL,\n\t`density` real DEFAULT 0 NOT NULL,\n\t`threshold` real NOT NULL,\n\t`recommendation_id` text,\n\t`redirect_gate_id` text,\n\t`assigned_volunteer_ids` text DEFAULT '[]' NOT NULL,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`gate_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE TABLE `crowd_snapshots` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`zone_id` text NOT NULL,\n\t`captured_at` text NOT NULL,\n\t`count` integer NOT NULL,\n\t`density` real NOT NULL,\n\t`flow_rate` real DEFAULT 0 NOT NULL,\n\t`confidence` real NOT NULL,\n\t`trend` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `crowd_snapshots_zone_time_idx` ON `crowd_snapshots` (`venue_id`,`zone_id`,`captured_at`);",
    "CREATE TABLE `fan_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`ticket_id` text,\n\t`venue_id` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`locale` text DEFAULT 'en' NOT NULL,\n\t`accessibility_profile` text,\n\t`expires_at` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`ticket_id`) REFERENCES `tickets`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `fan_sessions_token_unique` ON `fan_sessions` (`token_hash`);",
    "CREATE TABLE `gate_states` (\n\t`gate_id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`status` text NOT NULL,\n\t`queue_minutes` real DEFAULT 0 NOT NULL,\n\t`throughput` integer DEFAULT 0 NOT NULL,\n\t`current_count` integer DEFAULT 0 NOT NULL,\n\t`capacity` integer NOT NULL,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`gate_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE TABLE `incidents` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`zone_id` text NOT NULL,\n\t`category` text NOT NULL,\n\t`severity` text NOT NULL,\n\t`status` text NOT NULL,\n\t`reporter_id` text NOT NULL,\n\t`reporter_role` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`description` text,\n\t`assignee_id` text,\n\t`attachment_ids` text DEFAULT '[]' NOT NULL,\n\t`client_request_id` text NOT NULL,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`correlation_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`resolved_at` text,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`assignee_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `incidents_client_request_unique` ON `incidents` (`client_request_id`);",
    "CREATE INDEX `incidents_queue_idx` ON `incidents` (`venue_id`,`status`,`severity`,`created_at`);",
    "CREATE TABLE `matches` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`home_label` text NOT NULL,\n\t`away_label` text NOT NULL,\n\t`starts_at` text NOT NULL,\n\t`status` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE TABLE `notifications` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`audience` text NOT NULL,\n\t`zone_id` text,\n\t`locale` text NOT NULL,\n\t`channel` text NOT NULL,\n\t`message` text NOT NULL,\n\t`status` text NOT NULL,\n\t`client_request_id` text,\n\t`sent_at` text,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `notifications_client_request_unique` ON `notifications` (`client_request_id`);",
    "CREATE TABLE `recommendations` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`context_type` text NOT NULL,\n\t`context_id` text NOT NULL,\n\t`summary` text NOT NULL,\n\t`risk_level` text NOT NULL,\n\t`confidence` real NOT NULL,\n\t`evidence` text NOT NULL,\n\t`proposed_actions` text NOT NULL,\n\t`limitations` text DEFAULT '[]' NOT NULL,\n\t`status` text NOT NULL,\n\t`operator_decision` text,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `recommendations_venue_idx` ON `recommendations` (`venue_id`,`status`,`created_at`);",
    "CREATE TABLE `route_edges` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`from_node_id` text NOT NULL,\n\t`to_node_id` text NOT NULL,\n\t`distance` real NOT NULL,\n\t`expected_time_seconds` real NOT NULL,\n\t`capacity` integer NOT NULL,\n\t`live_density` real DEFAULT 0 NOT NULL,\n\t`status` text DEFAULT 'open' NOT NULL,\n\t`has_stairs` integer DEFAULT false NOT NULL,\n\t`has_lift` integer DEFAULT false NOT NULL,\n\t`has_ramp` integer DEFAULT false NOT NULL,\n\t`is_indoor` integer DEFAULT true NOT NULL,\n\t`sensory_intensity` text DEFAULT 'medium' NOT NULL,\n\t`slope` real DEFAULT 0 NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`from_node_id`) REFERENCES `route_nodes`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`to_node_id`) REFERENCES `route_nodes`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `route_edges_from_idx` ON `route_edges` (`venue_id`,`from_node_id`);",
    "CREATE TABLE `route_nodes` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`type` text NOT NULL,\n\t`x` real NOT NULL,\n\t`y` real NOT NULL,\n\t`floor` integer DEFAULT 0 NOT NULL,\n\t`zone_id` text,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `route_nodes_venue_idx` ON `route_nodes` (`venue_id`);",
    "CREATE TABLE `staff_sessions` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`user_id` text NOT NULL,\n\t`role` text NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`expires_at` text NOT NULL,\n\t`created_at` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `staff_sessions_token_unique` ON `staff_sessions` (`token_hash`);",
    "CREATE TABLE `tasks` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`incident_id` text,\n\t`assignee_id` text,\n\t`priority` text NOT NULL,\n\t`status` text NOT NULL,\n\t`title` text NOT NULL,\n\t`instructions` text NOT NULL,\n\t`zone_id` text NOT NULL,\n\t`due_at` text,\n\t`client_request_id` text,\n\t`version` integer DEFAULT 0 NOT NULL,\n\t`correlation_id` text NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\t`completed_at` text,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`incident_id`) REFERENCES `incidents`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`assignee_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `tasks_client_request_unique` ON `tasks` (`client_request_id`);",
    "CREATE INDEX `tasks_assignee_idx` ON `tasks` (`assignee_id`,`status`,`priority`,`created_at`);",
    "CREATE TABLE `tickets` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`match_id` text NOT NULL,\n\t`gate_id` text NOT NULL,\n\t`section` text NOT NULL,\n\t`row` text NOT NULL,\n\t`seat` text NOT NULL,\n\t`token_hash` text NOT NULL,\n\t`status` text DEFAULT 'valid' NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`match_id`) REFERENCES `matches`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`gate_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE UNIQUE INDEX `tickets_token_hash_unique` ON `tickets` (`token_hash`);",
    "CREATE UNIQUE INDEX `tickets_match_seat_unique` ON `tickets` (`match_id`,`section`,`row`,`seat`);",
    "CREATE TABLE `users` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`role` text NOT NULL,\n\t`display_name` text NOT NULL,\n\t`locale` text DEFAULT 'en' NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`email` text,\n\t`password_hash` text,\n\t`badge_id` text,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
    "CREATE UNIQUE INDEX `users_email_unique` ON `users` (`email`);",
    "CREATE UNIQUE INDEX `users_badge_unique` ON `users` (`badge_id`);",
    "CREATE TABLE `venues` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`timezone` text NOT NULL,\n\t`status` text DEFAULT 'active' NOT NULL,\n\t`capacity` integer NOT NULL,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL\n);",
    "CREATE TABLE `volunteer_profiles` (\n\t`user_id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`role_type` text NOT NULL,\n\t`zone_id` text NOT NULL,\n\t`shift_start` text NOT NULL,\n\t`shift_end` text NOT NULL,\n\t`status` text DEFAULT 'available' NOT NULL,\n\t`display_name` text NOT NULL,\n\tFOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`zone_id`) REFERENCES `zones`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE TABLE `zones` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`venue_id` text NOT NULL,\n\t`name` text NOT NULL,\n\t`type` text NOT NULL,\n\t`capacity` integer NOT NULL,\n\t`x` real NOT NULL,\n\t`y` real NOT NULL,\n\t`width` real,\n\t`height` real,\n\t`created_at` text NOT NULL,\n\t`updated_at` text NOT NULL,\n\tFOREIGN KEY (`venue_id`) REFERENCES `venues`(`id`) ON UPDATE no action ON DELETE no action\n);",
    "CREATE INDEX `zones_venue_idx` ON `zones` (`venue_id`);",
  ],
];
